-- MySQL Script generated by MySQL Workbench
-- Mon Apr  8 16:01:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinema` DEFAULT CHARACTER SET utf8 ;
USE `cinema` ;

-- -----------------------------------------------------
-- Table `cinema`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`users` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `birthday` DATE NOT NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 'USER',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`events` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `base_price` DOUBLE NOT NULL,
  `rating` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`auditoriums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`auditoriums` (
  `name` VARCHAR(25) NOT NULL,
  `amount_of_seats` BIGINT(5) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`vip_seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`vip_seats` (
  `auditoriums_name` VARCHAR(25) NOT NULL,
  `number` BIGINT(5) NOT NULL,
  PRIMARY KEY (`auditoriums_name`, `number`),
  INDEX `fk_vip_seats_auditoriums1_idx` (`auditoriums_name` ASC),
  CONSTRAINT `fk_vip_seats_auditoriums1`
    FOREIGN KEY (`auditoriums_name`)
    REFERENCES `cinema`.`auditoriums` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`auditoriums_has_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`auditoriums_has_event` (
  `auditoriums_name` VARCHAR(25) NOT NULL,
  `air_date` DATETIME NOT NULL,
  `events_id` BIGINT(10) NOT NULL,
  PRIMARY KEY (`auditoriums_name`, `air_date`),
  INDEX `fk_auditoriums_has_event_auditoriums1_idx` (`auditoriums_name` ASC),
  INDEX `fk_auditoriums_has_event_events1_idx` (`events_id` ASC),
  CONSTRAINT `fk_auditoriums_has_event_auditoriums1`
    FOREIGN KEY (`auditoriums_name`)
    REFERENCES `cinema`.`auditoriums` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_auditoriums_has_event_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `cinema`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`orders` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `price` DOUBLE NOT NULL,
  `users_id` BIGINT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cinema`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`tickets` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `seat` BIGINT(10) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `events_id` BIGINT(10) NOT NULL,
  `orders_id` BIGINT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_events1_idx` (`events_id` ASC),
  INDEX `fk_tickets_orders1_idx` (`orders_id` ASC),
  CONSTRAINT `fk_tickets_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `cinema`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tickets_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `cinema`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`statistics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(45) NOT NULL,
  `amount` BIGINT(10) NOT NULL,
  `users_id` BIGINT(10) NULL,
  `events_id` BIGINT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_satistics_users1_idx` (`users_id` ASC),
  INDEX `fk_satistics_events1_idx` (`events_id` ASC),
  CONSTRAINT `fk_satistics_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cinema`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_satistics_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `cinema`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
